
import React, { createContext, useContext, useState, useEffect } from 'react';

// Types of available languages
type Language = 'fr' | 'en' | 'ar' | 'es';

// Language context content
interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translations
const translations = {
  fr: {
    'nav.home': 'Accueil',
    'nav.offers': 'Nos Offres',
    'nav.how': 'Comment ça marche',
    'nav.contact': 'Contact',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.dashboard': 'Tableau de bord',
    'nav.orders': 'Mes commandes',
    'nav.logout': 'Déconnexion',
    'hero.title': 'Donnez vie à vos conversations',
    'hero.subtitle': 'Transformez vos échanges WhatsApp, Messenger, et Instagram en livres souvenirs personnalisés, parfaits pour célébrer vos relations en toute confidentialité et en toute sécurité.',
    'hero.createBook': 'Créer mon livre',
    'hero.discoverOffers': 'Découvrir ',
    'offers.title': 'Nos Offres',
    'offers.subtitle': 'Choisissez le format qui correspond le mieux à vos souvenirs et à votre budget',
    'offers.customQuote': 'Demander un devis sur mesure',
    'offers.specific': 'Vous avez des besoins spécifiques ou vous souhaitez une offre personnalisée ?',
    'cta.title': 'Prêt à transformer vos conversations en souvenirs ?',
    'cta.subtitle': 'Commencez dès aujourd\'hui et recevez votre livre souvenir personnalisé en quelques jours seulement. Un cadeau parfait pour les occasions spéciales ou pour vous faire plaisir.',
    'cta.button': 'Créer mon livre souvenir',
    'payment.title': 'Options de paiement',
    'payment.subtitle': 'Choisissez votre méthode de paiement préférée pour valider votre commande.',
    'payment.success': 'Paiement réussi',
    'payment.error': 'Erreur de paiement',
    'payment.processing': 'Traitement en cours...',
    'extract.title': 'Importer vos conversations',
    'extract.subtitle': 'Sélectionnez une plateforme et importez vos messages',
    'extract.whatsapp': 'WhatsApp',
    'extract.messenger': 'Messenger',
    'extract.instagram': 'Instagram',
    'extract.telegram': 'Telegram',
    'extract.upload': 'Téléverser le fichier',
    'extract.connect': 'Se connecter',
    'extract.filter': 'Filtrer les messages',
    'extract.preview': 'Aperçu',
    'extract.continue': 'Continuer',
    'message.1': 'Bonjour ! Je pense à toi aujourd\'hui. Comment vas-tu ?',
    'message.2': 'Salut ! Ça fait plaisir de te lire. Tout va bien, je prépare une surprise pour toi !',
    'status.online': 'En ligne',  // Message "en ligne"
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.noAccount': 'Pas encore de compte?',
    'auth.createAccount': 'Créer un compte',
    'auth.hasAccount': 'Vous avez déjà un compte?',
    'auth.passwordConfirm': 'Confirmer le mot de passe',
    'auth.signIn': 'Se connecter',
    'auth.signUp': "S'inscrire",
    'auth.submitting': 'Traitement en cours...',
    'auth.error': 'Erreur',
    'auth.success': 'Succès',
    'auth.loginSuccess': 'Connexion réussie!',
    'auth.registerSuccess': 'Inscription réussie! Vous pouvez maintenant vous connecter.',
    'auth.loginError': 'Échec de connexion. Veuillez réessayer.',
    'auth.registerError': "Échec de l'inscription. Veuillez réessayer.",
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas.',
    'auth.passwordLength': 'Le mot de passe doit contenir au moins 8 caractères.',

    'cart.title': 'Votre Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.discover': 'Découvrez nos offres pour transformer vos conversations en souvenirs précieux.',
    'cart.discoverBtn': 'Découvrir nos offres',
    'cart.items': 'Articles',
    'cart.summary': 'Récapitulatif',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.total': 'Total',
    'cart.checkout': 'Procéder au paiement',
    'cart.format': 'Format',

    'dashboard.welcome': 'Bienvenue',
    'dashboard.createBook': 'Créer un livre',
    'dashboard.createBookDesc': 'Transformez vos conversations en souvenir',
    'dashboard.orders': 'Mes commandes',
    'dashboard.ordersDesc': 'Gérez vos commandes en cours',
    'dashboard.profile': 'Mon profil',
    'dashboard.profileDesc': 'Gérez vos informations personnelles',
    'dashboard.start': 'Commencer',
    'dashboard.viewOrders': 'Voir mes commandes',
    'dashboard.editProfile': 'Modifier mon profil',
    
    'profile.title': 'Paramètres du profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.personalInfoDesc': 'Mettez à jour vos informations de profil',
    'profile.security': 'Sécurité',
    'profile.securityDesc': 'Gérez la sécurité de votre compte',
    'profile.save': 'Enregistrer les modifications',
    'profile.currentPassword': 'Mot de passe actuel',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmPassword': 'Confirmer le nouveau mot de passe',
    'profile.changePassword': 'Changer le mot de passe',
    'profile.deactivate': 'Désactiver mon compte',
    'profile.deactivateConfirm': 'Êtes-vous absolument sûr?',
    'profile.deactivateDesc': 'Cette action est permanente. Elle désactivera votre compte et toutes vos données seront conservées conformément à notre politique de confidentialité.',
    'profile.cancel': 'Annuler',
    
    'extract.guide.title': 'Guide d\'extraction des conversations',
    'extract.guide.whatsapp': 'Comment exporter vos conversations WhatsApp',
    'extract.guide.instagram': 'Comment exporter vos conversations Instagram',
    'extract.guide.facebook': 'Comment exporter vos conversations Facebook',
    'extract.whatsapp.step1': 'Ouvrez la conversation que vous souhaitez exporter dans WhatsApp.',
    'extract.whatsapp.step2': 'Appuyez sur les trois points (menu) en haut à droite de l\'écran.',
    'extract.whatsapp.step3': 'Sélectionnez "Plus" puis "Exporter la discussion".',
    'extract.whatsapp.step4': 'Choisissez "Sans médias" ou "Inclure les médias" selon vos préférences.',
    'extract.whatsapp.step5': 'Enregistrez le fichier ZIP ou TXT généré. Vous pourrez ensuite le télécharger sur notre plateforme.',
    'extract.instagram.step1': 'Connectez-vous à Instagram sur votre navigateur web (instagram.com).',
    'extract.instagram.step2': 'Cliquez sur votre photo de profil en haut à droite puis sur "Paramètres".',
    'extract.instagram.step3': 'Sélectionnez "Confidentialité et sécurité", puis descendez jusqu\'à "Télécharger les données".',
    'extract.instagram.step4': 'Entrez votre adresse e-mail et mot de passe pour confirmer la demande.',
    'extract.instagram.step5': 'Vous recevrez un lien par e-mail pour télécharger vos données dans les 48 heures.',
    'extract.facebook.step1': 'Accédez à Facebook dans votre navigateur et connectez-vous.',
    'extract.facebook.step2': 'Cliquez sur la flèche vers le bas en haut à droite puis sur "Paramètres et confidentialité".',
    'extract.facebook.step3': 'Sélectionnez "Paramètres" puis "Vos informations Facebook".',
    'extract.facebook.step4': 'Cliquez sur "Télécharger vos informations" et sélectionnez "Messages" uniquement.',
    'extract.facebook.step5': 'Choisissez le format JSON et cliquez sur "Créer un fichier". Vous recevrez une notification lorsque votre fichier sera prêt à télécharger.',
    'extract.continue.with': 'Continuer avec',
    'extract.nextSteps': 'Les prochaines étapes',
    'extract.personalization': 'Personnalisation',
    'extract.personalizationDesc': 'Choisissez votre style, polices, et couleurs pour créer un livre unique.',
    'extract.steps.preview': 'Aperçu',
    'extract.previewDesc': 'Visualisez votre livre et ajustez-le jusqu\'à ce qu\'il soit parfait.',
    'extract.order': 'Commande',
    'extract.orderDesc': 'Finalisez votre commande et attendez la livraison de votre souvenir.',
    
    'extract.error.general': 'Erreur',
    'extract.error.selectFile': 'Veuillez sélectionner un fichier à traiter.',
    'extract.success': 'Succès',
    'extract.messagesExtracted': 'messages extraits avec succès.',
    'extract.processingError': 'Une erreur est survenue lors du traitement du fichier.',
    'extract.uploadFile': 'Téléverser un fichier',
    'extract.acceptedFormats': 'ZIP, TXT ou JSON. Max 10MB',
    'extract.processing': 'Traitement en cours...',
    'extract.processFile': 'Traiter le fichier',
    'extract.description': 'Transformez vos conversations en un beau livre souvenir.',
    'orders.description': 'Consultez et suivez vos commandes de livres souvenir.',
    'profile.description': 'Gérez vos préférences et informations personnelles.'
  },
  en: {
    'nav.home': 'Home',
    'nav.offers': 'Our Offers',
    'nav.how': 'How It Works',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'My Orders',
    'nav.logout': 'Logout',
    'hero.title': 'Give life to your conversations',
    'hero.subtitle': 'Transform your WhatsApp, Messenger, and Instagram exchanges into personalized souvenir books, perfect for celebrating your relationships with complete privacy and security.',
    'hero.createBook': 'Create my book',
    'hero.discoverOffers': 'Discover our offers',
    'offers.title': 'Our Offers',
    'offers.subtitle': 'Choose the format that best matches your memories and your budget',
    'offers.customQuote': 'Request a custom quote',
    'offers.specific': 'Do you have specific needs or would you like a personalized offer?',
    'cta.title': 'Ready to transform your conversations into memories?',
    'cta.subtitle': 'Start today and receive your personalized souvenir book in just a few days. A perfect gift for special occasions or to treat yourself.',
    'cta.button': 'Create my souvenir book',
    'payment.title': 'Payment options',
    'payment.subtitle': 'Choose your preferred payment method to validate your order.',
    'payment.success': 'Payment successful',
    'payment.error': 'Payment error',
    'payment.processing': 'Processing...',
    'extract.title': 'Import your conversations',
    'extract.subtitle': 'Select a platform and import your messages',
    'extract.whatsapp': 'WhatsApp',
    'extract.messenger': 'Messenger',
    'extract.instagram': 'Instagram',
    'extract.telegram': 'Telegram',
    'extract.upload': 'Upload file',
    'extract.connect': 'Connect',
    'extract.filter': 'Filter messages',
    'extract.preview': 'Preview',
    'extract.continue': 'Continue',
    'hello.amadou': 'Hello Amadou',
    'message.1': 'Hello! I\'m thinking about you today. How are you?',
    'message.2': 'Hi! It\'s great to hear from you. Everything is fine, I\'m preparing a surprise for you!',
    'status.online': 'Online',  // Message "online"
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.createAccount': 'Create an account',
    'auth.hasAccount': 'Already have an account?',
    'auth.passwordConfirm': 'Confirm password',
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign up',
    'auth.submitting': 'Processing...',
    'auth.error': 'Error',
    'auth.success': 'Success',
    'auth.loginSuccess': 'Login successful!',
    'auth.registerSuccess': 'Registration successful! You can now log in.',
    'auth.loginError': 'Login failed. Please try again.',
    'auth.registerError': 'Registration failed. Please try again.',
    'auth.passwordMismatch': 'Passwords do not match.',
    'auth.passwordLength': 'Password must be at least 8 characters long.',

    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.discover': 'Discover our offers to transform your conversations into precious memories.',
    'cart.discoverBtn': 'Discover our offers',
    'cart.items': 'Items',
    'cart.summary': 'Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to checkout',
    'cart.format': 'Format',

    'dashboard.welcome': 'Welcome',
    'dashboard.createBook': 'Create a book',
    'dashboard.createBookDesc': 'Transform your conversations into memories',
    'dashboard.orders': 'My orders',
    'dashboard.ordersDesc': 'Manage your current orders',
    'dashboard.profile': 'My profile',
    'dashboard.profileDesc': 'Manage your personal information',
    'dashboard.start': 'Start',
    'dashboard.viewOrders': 'View my orders',
    'dashboard.editProfile': 'Edit my profile',
    
    'profile.title': 'Profile Settings',
    'profile.personalInfo': 'Personal Information',
    'profile.personalInfoDesc': 'Update your profile information',
    'profile.security': 'Security',
    'profile.securityDesc': 'Manage your account security',
    'profile.save': 'Save changes',
    'profile.currentPassword': 'Current password',
    'profile.newPassword': 'New password',
    'profile.confirmPassword': 'Confirm new password',
    'profile.changePassword': 'Change password',
    'profile.deactivate': 'Deactivate my account',
    'profile.deactivateConfirm': 'Are you absolutely sure?',
    'profile.deactivateDesc': 'This action is permanent. It will deactivate your account and all your data will be kept in accordance with our privacy policy.',
    'profile.cancel': 'Cancel',
    
    'extract.guide.title': 'Conversation Extraction Guide',
    'extract.guide.whatsapp': 'How to export your WhatsApp conversations',
    'extract.guide.instagram': 'How to export your Instagram conversations',
    'extract.guide.facebook': 'How to export your Facebook conversations',
    'extract.whatsapp.step1': 'Open the conversation you want to export in WhatsApp.',
    'extract.whatsapp.step2': 'Tap the three dots (menu) in the top right of the screen.',
    'extract.whatsapp.step3': 'Select "More" then "Export chat".',
    'extract.whatsapp.step4': 'Choose "Without media" or "Include media" according to your preferences.',
    'extract.whatsapp.step5': 'Save the generated ZIP or TXT file. You can then upload it to our platform.',
    'extract.instagram.step1': 'Log in to Instagram on your web browser (instagram.com).',
    'extract.instagram.step2': 'Click on your profile picture in the top right then on "Settings".',
    'extract.instagram.step3': 'Select "Privacy and Security", then scroll down to "Download Data".',
    'extract.instagram.step4': 'Enter your email address and password to confirm the request.',
    'extract.instagram.step5': 'You will receive a link by email to download your data within 48 hours.',
    'extract.facebook.step1': 'Go to Facebook in your browser and log in.',
    'extract.facebook.step2': 'Click the down arrow in the top right then on "Settings & Privacy".',
    'extract.facebook.step3': 'Select "Settings" then "Your Facebook Information".',
    'extract.facebook.step4': 'Click on "Download Your Information" and select "Messages" only.',
    'extract.facebook.step5': 'Choose JSON format and click "Create File". You will receive a notification when your file is ready to download.',
    'extract.continue.with': 'Continue with',
    'extract.nextSteps': 'The next steps',
    'extract.personalization': 'Personalization',
    'extract.personalizationDesc': 'Choose your style, fonts, and colors to create a unique book.',
    'extract.steps.preview': 'Preview',
    'extract.previewDesc': 'Visualize your book and adjust it until it\'s perfect.',
    'extract.order': 'Order',
    'extract.orderDesc': 'Finalize your order and wait for the delivery of your memory book.',
    
    'extract.error.general': 'Error',
    'extract.error.selectFile': 'Please select a file to process.',
    'extract.success': 'Success',
    'extract.messagesExtracted': 'messages extracted successfully.',
    'extract.processingError': 'An error occurred while processing the file.',
    'extract.uploadFile': 'Upload a file',
    'extract.acceptedFormats': 'ZIP, TXT or JSON. Max 10MB',
    'extract.processing': 'Processing...',
    'extract.processFile': 'Process file',
    'extract.description': 'Transform your conversations into a beautiful souvenir book.',
    'orders.description': 'Check and track your souvenir book orders.',
    'profile.description': 'Manage your preferences and personal information.'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.offers': 'Nuestras Ofertas',
    'nav.how': 'Cómo Funciona',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.dashboard': 'Panel de Control',
    'nav.orders': 'Mis Pedidos',
    'nav.logout': 'Cerrar Sesión',
    'hero.title': 'Da vida a tus conversaciones',
    'hero.subtitle': 'Transforma tus intercambios de WhatsApp, Messenger e Instagram en libros de recuerdos personalizados, perfectos para celebrar tus relaciones con total confidencialidad y seguridad.',
    'hero.createBook': 'Crear mi libro',
    'hero.discoverOffers': 'Descubrir nuestras ofertas',
    'offers.title': 'Nuestras Ofertas',
    'offers.subtitle': 'Elige el formato que mejor se adapte a tus recuerdos y presupuesto',
    'offers.customQuote': 'Solicitar presupuesto personalizado',
    'offers.specific': '¿Tienes necesidades específicas o deseas una oferta personalizada?',
    'cta.title': '¿Listo para transformar tus conversaciones en recuerdos?',
    'cta.subtitle': 'Comienza hoy y recibe tu libro de recuerdos personalizado en pocos días. Un regalo perfecto para ocasiones especiales.',
    'cta.button': 'Crear mi libro de recuerdos',
    'payment.title': 'Opciones de pago',
    'payment.subtitle': 'Elije tu método de pago preferido para validar tu pedido.',
    'payment.success': 'Pago exitoso',
    'payment.error': 'Error de pago',
    'payment.processing': 'Procesando...',
    'extract.title': 'Importar tus conversaciones',
    'extract.subtitle': 'Selecciona una plataforma e importa tus mensajes',
    'extract.whatsapp': 'WhatsApp',
    'extract.messenger': 'Messenger',
    'extract.instagram': 'Instagram',
    'extract.telegram': 'Telegram',
    'extract.upload': 'Subir archivo',
    'extract.connect': 'Conectar',
    'extract.filter': 'Filtrar mensajes',
    'extract.preview': 'Vista previa',
    'extract.continue': 'Continuar',
    'message.1': '¡Hola! Estoy pensando en ti hoy. ¿Cómo estás?',
    'message.2': '¡Hola! Me alegra saber de ti. Todo va bien, ¡estoy preparando una sorpresa para ti!',
    'status.online': 'En línea',  // Message "en línea"
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.forgotPassword': '¿Olvidó su contraseña?',
    'auth.noAccount': '¿No tiene una cuenta?',
    'auth.createAccount': 'Crear una cuenta',
    'auth.hasAccount': '¿Ya tiene una cuenta?',
    'auth.passwordConfirm': 'Confirmar contraseña',
    'auth.signIn': 'Iniciar sesión',
    'auth.signUp': 'Registrarse',
    'auth.submitting': 'Procesando...',
    'auth.error': 'Error',
    'auth.success': 'Éxito',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.registerSuccess': '¡Registro exitoso! Ahora puede iniciar sesión.',
    'auth.loginError': 'Error de inicio de sesión. Por favor, inténtelo de nuevo.',
    'auth.registerError': 'Error de registro. Por favor, inténtelo de nuevo.',
    'auth.passwordMismatch': 'Las contraseñas no coinciden.',
    'auth.passwordLength': 'La contraseña debe tener al menos 8 caracteres.',

    'cart.title': 'Su Carrito',
    'cart.empty': 'Su carrito está vacío',
    'cart.discover': 'Descubra nuestras ofertas para transformar sus conversaciones en recuerdos preciosos.',
    'cart.discoverBtn': 'Descubrir nuestras ofertas',
    'cart.items': 'Artículos',
    'cart.summary': 'Resumen',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al pago',
    'cart.format': 'Formato',

    'dashboard.welcome': 'Bienvenido',
    'dashboard.createBook': 'Crear un libro',
    'dashboard.createBookDesc': 'Transforme sus conversaciones en recuerdos',
    'dashboard.orders': 'Mis pedidos',
    'dashboard.ordersDesc': 'Gestione sus pedidos actuales',
    'dashboard.profile': 'Mi perfil',
    'dashboard.profileDesc': 'Gestione su información personal',
    'dashboard.start': 'Comenzar',
    'dashboard.viewOrders': 'Ver mis pedidos',
    'dashboard.editProfile': 'Editar mi perfil',
    
    'profile.title': 'Configuración del perfil',
    'profile.personalInfo': 'Información personal',
    'profile.personalInfoDesc': 'Actualice su información de perfil',
    'profile.security': 'Seguridad',
    'profile.securityDesc': 'Gestione la seguridad de su cuenta',
    'profile.save': 'Guardar cambios',
    'profile.currentPassword': 'Contraseña actual',
    'profile.newPassword': 'Nueva contraseña',
    'profile.confirmPassword': 'Confirmar nueva contraseña',
    'profile.changePassword': 'Cambiar contraseña',
    'profile.deactivate': 'Desactivar mi cuenta',
    'profile.deactivateConfirm': '¿Está absolutamente seguro?',
    'profile.deactivateDesc': 'Esta acción es permanente. Desactivará su cuenta y todos sus datos se conservarán de acuerdo con nuestra política de privacidad.',
    'profile.cancel': 'Cancelar',
    
    'extract.guide.title': 'Guía de extracción de conversaciones',
    'extract.guide.whatsapp': 'Cómo exportar sus conversaciones de WhatsApp',
    'extract.guide.instagram': 'Cómo exportar sus conversaciones de Instagram',
    'extract.guide.facebook': 'Cómo exportar sus conversaciones de Facebook',
    'extract.whatsapp.step1': 'Abra la conversación que desea exportar en WhatsApp.',
    'extract.whatsapp.step2': 'Toque los tres puntos (menú) en la parte superior derecha de la pantalla.',
    'extract.whatsapp.step3': 'Seleccione "Más" y luego "Exportar chat".',
    'extract.whatsapp.step4': 'Elija "Sin medios" o "Incluir medios" según sus preferencias.',
    'extract.whatsapp.step5': 'Guarde el archivo ZIP o TXT generado. Luego podrá subirlo a nuestra plataforma.',
    'extract.instagram.step1': 'Inicie sesión en Instagram en su navegador web (instagram.com).',
    'extract.instagram.step2': 'Haga clic en su foto de perfil en la parte superior derecha y luego en "Configuración".',
    'extract.instagram.step3': 'Seleccione "Privacidad y seguridad", luego desplácese hacia abajo hasta "Descargar datos".',
    'extract.instagram.step4': 'Ingrese su dirección de correo electrónico y contraseña para confirmar la solicitud.',
    'extract.instagram.step5': 'Recibirá un enlace por correo electrónico para descargar sus datos en las próximas 48 horas.',
    'extract.facebook.step1': 'Acceda a Facebook en su navegador e inicie sesión.',
    'extract.facebook.step2': 'Haga clic en la flecha hacia abajo en la parte superior derecha y luego en "Configuración y privacidad".',
    'extract.facebook.step3': 'Seleccione "Configuración" y luego "Su información de Facebook".',
    'extract.facebook.step4': 'Haga clic en "Descargar su información" y seleccione solo "Mensajes".',
    'extract.facebook.step5': 'Elija el formato JSON y haga clic en "Crear archivo". Recibirá una notificación cuando su archivo esté listo para descargar.',
    'extract.continue.with': 'Continuar con',
    'extract.nextSteps': 'Los próximos pasos',
    'extract.personalization': 'Personalización',
    'extract.personalizationDesc': 'Elija su estilo, fuentes y colores para crear un libro único.',
    'extract.steps.preview': 'Vista previa',
    'extract.previewDesc': 'Visualice su libro y ajústelo hasta que sea perfecto.',
    'extract.order': 'Pedido',
    'extract.orderDesc': 'Finalice su pedido y espere la entrega de su libro de recuerdos.',
    
    'extract.error.general': 'Error',
    'extract.error.selectFile': 'Por favor, seleccione un archivo para procesar.',
    'extract.success': 'Éxito',
    'extract.messagesExtracted': 'mensajes extraídos con éxito.',
    'extract.processingError': 'Se produjo un error al procesar el archivo.',
    'extract.uploadFile': 'Subir un archivo',
    'extract.acceptedFormats': 'ZIP, TXT o JSON. Máx 10MB',
    'extract.processing': 'Procesando...',
    'extract.processFile': 'Procesar archivo',
    'extract.description': 'Transforme sus conversaciones en un hermoso libro de recuerdos.',
    'orders.description': 'Consulte y realice un seguimiento de sus pedidos de libros de recuerdos.',
    'profile.description': 'Gestione sus preferencias e información personal.'
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.offers': 'عروضنا',
    'nav.how': 'كيف يعمل',
    'nav.contact': 'اتصل بنا',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.orders': 'طلباتي',
    'nav.logout': 'تسجيل الخروج',
    'hero.title': 'امنح محادثاتك الحياة',
    'hero.subtitle': 'حوّل محادثاتك على واتساب وماسنجر وإنستغرام إلى كتب تذكارية مخصصة، مثالية للاحتفال بعلاقاتك بكل خصوصية وأمان.'
,
    'hero.createBook': 'إنشاء كتابي',
    'hero.discoverOffers': 'اكتشف عروضنا',
    'offers.title': 'عروضنا',
    'offers.subtitle': 'اختر التنسيق الذي يناسب ذكرياتك وميزانيتك',
    'offers.customQuote': 'طلب عرض سعر مخصص',
    'offers.specific': 'هل لديك احتياجات محددة أو ترغب في الحصول على عرض مخصص؟',
    'cta.title': 'هل أنت مستعد لتحويل محادثاتك إلى ذكريات؟',
    'cta.subtitle': 'ابدأ اليوم واستلم كتاب الذكريات المخصص في غضون أيام قليلة. هدية مثالية للمناسبات الخاصة.',
    'cta.button': 'إنشاء كتاب الذكريات',
    'payment.title': 'خيارات الدفع',
    'payment.subtitle': 'اختر طريقة الدفع المفضلة لديك لتأكيد طلبك.',
    'payment.success': 'تم الدفع بنجاح',
    'payment.error': 'خطأ في الدفع',
    'payment.processing': 'جاري المعالجة...',
    'extract.title': 'استيراد محادثاتك',
    'extract.subtitle': 'اختر منصة واستورد رسائلك',
    'extract.whatsapp': 'واتساب',
    'extract.messenger': 'ماسنجر',
    'extract.instagram': 'انستغرام',
    'extract.telegram': 'تلغرام',
    'extract.upload': 'تحميل الملف',
    'extract.connect': 'اتصال',
    'extract.filter': 'تصفية الرسائل',
    'extract.preview': 'معاينة',
    'extract.continue': 'استمرار',
    'message.1': 'مرحباً! أفكر فيك اليوم. كيف حالك؟',
    'message.2': 'مرحباً! من الجيد سماع أخبارك. كل شيء على ما يرام، أنا أعد لك مفاجأة!',
    'status.online': 'متصل',  // Message "en ligne"
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.createAccount': 'إنشاء حساب',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.passwordConfirm': 'تأكيد كلمة المرور',
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.submitting': 'جاري المعالجة...',
    'auth.error': 'خطأ',
    'auth.success': 'نجاح',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح!',
    'auth.registerSuccess': 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
    'auth.loginError': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    'auth.registerError': 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    'auth.passwordMismatch': 'كلمات المرور غير متطابقة.',
    'auth.passwordLength': 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل.',

    'cart.title': 'سلة التسوق الخاصة بك',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.discover': 'اكتشف عروضنا لتحويل محادثاتك إلى ذكريات ثمينة.',
    'cart.discoverBtn': 'اكتشف عروضنا',
    'cart.items': 'العناصر',
    'cart.summary': 'ملخص',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.total': 'المجموع',
    'cart.checkout': 'إتمام الشراء',
    'cart.format': 'التنسيق',

    'dashboard.welcome': 'مرحباً',
    'dashboard.createBook': 'إنشاء كتاب',
    'dashboard.createBookDesc': 'حول محادثاتك إلى ذكريات',
    'dashboard.orders': 'طلباتي',
    'dashboard.ordersDesc': 'إدارة طلباتك الحالية',
    'dashboard.profile': 'ملفي الشخصي',
    'dashboard.profileDesc': 'إدارة معلوماتك الشخصية',
    'dashboard.start': 'ابدأ',
    'dashboard.viewOrders': 'عرض طلباتي',
    'dashboard.editProfile': 'تعديل ملفي الشخصي',
    
    'profile.title': 'إعدادات الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.personalInfoDesc': 'تحديث معلومات ملفك الشخصي',
    'profile.security': 'الأمان',
    'profile.securityDesc': 'إدارة أمان حسابك',
    'profile.save': 'حفظ التغييرات',
    'profile.currentPassword': 'كلمة المرور الحالية',
    'profile.newPassword': 'كلمة المرور الجديدة',
    'profile.confirmPassword': 'تأكيد كلمة المرور الجديدة',
    'profile.changePassword': 'تغيير كلمة المرور',
    'profile.deactivate': 'تعطيل حسابي',
    'profile.deactivateConfirm': 'هل أنت متأكد تماماً؟',
    'profile.deactivateDesc': 'هذا الإجراء دائم. سيؤدي إلى تعطيل حسابك وسيتم الاحتفاظ بجميع بياناتك وفقًا لسياسة الخصوصية الخاصة بنا.',
    'profile.cancel': 'إلغاء',
    
    'extract.guide.title': 'دليل استخراج المحادثات',
    'extract.guide.whatsapp': 'كيفية تصدير محادثاتك من واتساب',
    'extract.guide.instagram': 'كيفية تصدير محادثاتك من إنستغرام',
    'extract.guide.facebook': 'كيفية تصدير محادثاتك من فيسبوك',
    'extract.whatsapp.step1': 'افتح المحادثة التي تريد تصديرها في واتساب.',
    'extract.whatsapp.step2': 'انقر على النقاط الثلاث (القائمة) في أعلى اليمين من الشاشة.',
    'extract.whatsapp.step3': 'اختر "المزيد" ثم "تصدير الدردشة".',
    'extract.whatsapp.step4': 'اختر "بدون وسائط" أو "تضمين الوسائط" حسب تفضيلاتك.',
    'extract.whatsapp.step5': 'احفظ ملف ZIP أو TXT الذي تم إنشاؤه. يمكنك بعد ذلك تحميله على منصتنا.',
    'extract.instagram.step1': 'قم بتسجيل الدخول إلى إنستغرام على متصفح الويب الخاص بك (instagram.com).',
    'extract.instagram.step2': 'انقر على صورة ملفك الشخصي في أعلى اليمين ثم على "الإعدادات".',
    'extract.instagram.step3': 'اختر "الخصوصية والأمان"، ثم انتقل لأسفل إلى "تنزيل البيانات".',
    'extract.instagram.step4': 'أدخل عنوان بريدك الإلكتروني وكلمة المرور لتأكيد الطلب.',
    'extract.instagram.step5': 'ستتلقى رابطًا عبر البريد الإلكتروني لتنزيل بياناتك في غضون 48 ساعة.',
    'extract.facebook.step1': 'انتقل إلى فيسبوك في المتصفح الخاص بك وقم بتسجيل الدخول.',
    'extract.facebook.step2': 'انقر على السهم المتجه لأسفل في أعلى اليمين ثم على "الإعدادات والخصوصية".',
    'extract.facebook.step3': 'اختر "الإعدادات" ثم "معلومات فيسبوك الخاصة بك".',
    'extract.facebook.step4': 'انقر على "تنزيل معلوماتك" واختر "الرسائل" فقط.',
    'extract.facebook.step5': 'اختر تنسيق JSON وانقر على "إنشاء ملف". ستتلقى إشعارًا عندما يكون ملفك جاهزًا للتنزيل.',
    'extract.continue.with': 'متابعة مع',
    'extract.nextSteps': 'الخطوات التالية',
    'extract.personalization': 'التخصيص',
    'extract.personalizationDesc': 'اختر الأسلوب والخطوط والألوان لإنشاء كتاب فريد.',
    'extract.steps.preview': 'معاينة',
    'extract.previewDesc': 'شاهد كتابك وعدله حتى يصبح مثاليا.',
    'extract.order': 'الطلب',
    'extract.orderDesc': 'أكمل طلبك وانتظر تسليم كتاب ذكرياتك.',
    
    'extract.error.general': 'خطأ',
    'extract.error.selectFile': 'الرجاء تحديد ملف للمعالجة.',
    'extract.success': 'نجاح',
    'extract.messagesExtracted': 'تم استخراج الرسائل بنجاح.',
    'extract.processingError': 'حدث خطأ أثناء معالجة الملف.',
    'extract.uploadFile': 'تحميل ملف',
    'extract.acceptedFormats': 'ZIP، TXT أو JSON. الحد الأقصى 10 ميجابايت',
    'extract.processing': 'جاري المعالجة...',
    'extract.processFile': 'معالجة الملف',
    'extract.description': 'حوّل محادثاتك إلى كتاب تذكاري جميل.',
    'orders.description': 'تحقق وتتبع طلبات كتاب الذكريات الخاصة بك.',
    'profile.description': 'قم بإدارة تفضيلاتك ومعلوماتك الشخصية.'
  }
};

// Creating the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'fr',
  toggleLanguage: () => {},
  setLanguage: () => {},
  t: () => ''
});

// Provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  // Load language preference from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['fr', 'en', 'ar', 'es'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language);
    // Update document direction for RTL languages (Arabic)
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  // Toggle between languages
  const toggleLanguage = () => {
    setLanguage(prev => {
      if (prev === 'fr') return 'en';
      if (prev === 'en') return 'es';
      if (prev === 'es') return 'ar';
      return 'fr';
    });
  };

  // Translation function
  const t = (key: string): string => {
    const langDict = translations[language] || translations.fr;
    return langDict[key as keyof typeof langDict] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

